/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hangman;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasWordList() {
        App testClass = new App();
        assertNotNull(testClass, "app should have a greeting");
    }
}
