/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hangman;

import java.util.ArrayList;

public class App {

    public void getDrawings() {
        ArrayList<String> drawings = new Drawings().getDrawings();
        System.out.println(drawings);
    }

    public static void main(String[] args) {

        new App().getDrawings();
    }

}
