/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Hangman;

import java.io.IOException;

public class App {

    public static void main(String[] args) throws IOException {

        System.out.println("Test Statements: App");
        System.out.println("Welcome");

        Gameword gameword = new Gameword();
        gameword.test();

    }

}
